client:
  port: ${app.port}
  forward-headers-strategy: framework

spring:
  mail:
    default-encoding: UTF-8
    host: ${mail.host}
    username: ${mail.username}
    password: ${mail.password}
    port: ${mail.port}
    protocol: smtp
    tls: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

libraryserv:
  book:
    add: ${add-book}
    get: ${get-book}
    get-bytes: ${get-bytes}
    delete: ${delete-book}
  user:
    registration: ${reg-user}
    validation: ${valid-user}
    authorization: ${auth-user}
  server:
    health-check: ${health-check}
  file-storage:
    upload-dir: ${upload-dir}
  email:
    to: ${email.recipient-address}
    from: ${email.sender-address}
    subject-server-unavailable: ${email.message.subject-server-unavailable}
    subject-cannot-delete-book: ${email.message.subject-cannot-delete-book}
    template-server-unavailable: ${email.message.template-server-unavailable}
    template-cannot-delete-book: ${email.message.template-cannot-delete-book}