client:
  port: ${app.port}
  forward-headers-strategy: framework

bookshelf:
  book:
    add: ${add-book}
    get: ${get-book}
    get-book-bytes: ${get-book-bytes}
    delete: ${delete-book}
  user:
    registration: ${reg-user}
    validation: ${valid-user}
    authorization: ${auth-user}